# apps/api/Dockerfile
FROM oven/bun:1.3.2-alpine AS base
WORKDIR /app

# Install deps first (better caching)
COPY package.json bun.lock ./
RUN bun install

COPY prisma ./prisma
COPY tsconfig*.json ./
COPY src ./src

RUN bunx prisma generate

RUN bunx nest build

# Runtime image
FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production

RUN apk add --no-cache bash

COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/dist ./dist
COPY --from=base /app/prisma ./prisma


EXPOSE 3000
COPY docker-entrypoint.sh ./docker-entrypoint.sh
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
